name: Invoke API Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make API request
        run: |
          curl -X GET "https://5min-read.vercel.app/api/deletecollection"
